# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='grades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongs_id', models.IntegerField()),
                ('academisc', models.CharField(max_length=255, null=True)),
                ('semester', models.CharField(max_length=255, null=True)),
                ('courseCode', models.CharField(max_length=255, null=True)),
                ('number', models.CharField(max_length=255)),
                ('courseName', models.TextField()),
                ('courseType', models.TextField(null=True)),
                ('credit', models.CharField(max_length=255, null=True)),
                ('totalGrade', models.TextField(null=True)),
                ('makeupGrade', models.TextField(null=True)),
                ('finalGrade', models.TextField(null=True)),
                ('gradePoint', models.CharField(max_length=255, null=True)),
                ('updateTime', models.CharField(max_length=19)),
            ],
            options={
                'ordering': ['belongs_id'],
            },
        ),
        migrations.CreateModel(
            name='information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.TextField()),
                ('url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'ordering': ['school'],
            },
        ),
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('belongs_id', models.IntegerField()),
                ('username', models.CharField(max_length=25)),
                ('name', models.TextField(null=True)),
                ('password', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=255, null=True)),
                ('school', models.TextField()),
                ('verify', models.BooleanField()),
                ('updateTime', models.TimeField(auto_now=True)),
            ],
            options={
                'ordering': ['belongs_id'],
            },
        ),
    ]
