# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grade', '0002_kuaidiinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='kuaidiinfo',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
